#!/bin/sh
# design-sync post-build step: copy the public/ assets the authored previews
# reference by absolute path (FoxAvatar, JourneyScene, WalkingFoxRear,
# PosedFox, FoxCharacter). ds-bundle/ is regenerated by package-build.mjs on
# every run, so this must be re-run after each build, before validate/capture.
set -e
cd "$(dirname "$0")/../.."
mkdir -p ds-bundle/journey ds-bundle/fox ds-bundle/foxcapture
cp public/journey/ChatSiSiProfile.png ds-bundle/journey/
cp public/journey/HomeScreen.png ds-bundle/journey/
cp public/fox/walking-clean.webp ds-bundle/fox/
cp public/fox/walking-rear.webp ds-bundle/fox/
cp public/foxcapture/sitting-front.png ds-bundle/foxcapture/
echo "[copy-assets] copied journey/fox/foxcapture preview assets into ds-bundle/"
